-- ============================================================
-- SecureVote Seed Data (DEVELOPMENT ONLY)
-- ============================================================
-- WARNING: These credentials are for development/testing only.
-- Do NOT use these in any production environment.
-- ============================================================

USE secure_voting_db;

-- Admin user (password: Admin@123, hashed via Werkzeug)
-- The actual hash should be generated by the seed.py script.
-- This file is provided as a reference for manual DB seeding.

-- See backend/seed.py for the Python-based seeder that properly
-- hashes passwords and generates face embeddings.
